### ISSUE TITLE
Web poorui项目结构问题导致docker无法构建镜像

### ISSUE THREAD

**Issue by ek1ng** [team-s2/ACTF-2022#1]
使用当时下载的附件可以成功运行
![image](https://user-images.githubusercontent.com/72065582/177723697-00122b5f-0ff5-40ef-8935-8f10a28cc111.png)
但是使用从仓库下载的附件无法成功运行docker，报错找不到.source目录，发现当时题目给出的附件里项目目录结构和仓库中的项目目录结构不同导致无法运行
![image](https://user-images.githubusercontent.com/72065582/177723557-e5c92cb4-c0d3-48c6-a8c9-5dbee5aa711c.png)
此时目录结构
![image](https://user-images.githubusercontent.com/72065582/177725876-4b68cc88-fa23-4b60-b058-bdc811b32900.png)
与dockerfile匹配的目录结构
![image](https://user-images.githubusercontent.com/72065582/177726111-6f13f7db-0c87-467c-9d27-b63565d71bab.png)

**Comment by PumpkinDemo** [comment]
we have altered the directory structure of "poorui"
